### ISSUE TITLE
the SHA result in the paper is wrong?

### ISSUE THREAD

**Issue by aa200647963** [dongxingning/SHA-GCL-for-SGG#2]
![image](https://user-images.githubusercontent.com/50197630/161182116-103d7ee3-8348-4103-9e5b-04e069265e38.png)
This is my reproduce of TransLike-SHA, the mR@50 is 16.40, but in the paper the mR@50 is 20.8. Could you tell me the reason? Or the results of your paper are not credible?

**Comment by dongxingning** [comment]
Thanks for your question. Actually, SHA is not a debiasing method, so it would keep stable on the biased metric (R@k), but may be sensitive to the hardware conditions or parameter initialization on the unbiased metric (mR@k). If you still have doubts about our experimental results, we can provide the corresponding checkpoint or .log files for you to check.

**Comment by rafa-cxg** [comment]
Hi, I am facing performence problem too, could you please provide the corresponding .log files and checkpoints  for us to check? Thanks

> Thanks for your question. Actually, SHA is not a debiasing method, so it would keep stable on the biased metric (R@k), but may be sensitive to the hardware conditions or parameter initialization on the unbiased metric (mR@k). If you still have doubts about our experimental results, we can provide the corresponding checkpoint or .log files for you to check.

**Comment by dongxingning** [comment]
> Hi, I am facing performence problem too, could you please provide the corresponding .log files and checkpoints for us to check? Thanks
We are willing to share the CHECKPOINT and LOG files, could you point out which experiment you would check (e.g., SHA-PredCls, SHAGCL-SGDet), we will provide a download link as soon as possible.
