### ISSUE TITLE
can not find where to map original rel_label index to decending index?

### ISSUE THREAD

**Issue by rafa-cxg** [dongxingning/SHA-GCL-for-SGG#3]
Hi, appreciate your work! 

I am confused that the code seems to use the original rel_label class indexes as each group's label. I was thought that the relation labels should be rearranged by new order. 

However,  `self.pre_group_matrix` seems to directly assign 0-5 to 51 predicates, without descending order before assignment.   
![image](https://user-images.githubusercontent.com/49938663/162654560-dff1022e-868f-488a-a137-04960257b38c.png)

**Comment by dongxingning** [comment]
Thanks for your question!
We indeed rearrange the rel_label class indexes in maskrcnn_benchmark/data/datasets/visual_genome.py [Line 389-392]. We hope you find it helpful.
![1649646011(1)](https://user-images.githubusercontent.com/58069157/162657952-d864f3d6-294e-4259-a131-b4ed91a2a44c.png)

**Comment by rafa-cxg** [comment]
yeah, thanks for that!
